version: '3.7'

services:
    spreadsheet-workers:
        container_name: "spreadsheet_worker"
        build:
            context: ./
            dockerfile: Spreadsheet.BackgroundWorker/Dockerfile
        image: "rhe89/hub-spreadsheet-worker"
        
    spreadsheet-api:
        container_name: "spreadsheet_api"
        build: 
            context: ./
            dockerfile: Spreadsheet.Web.Api/Dockerfile
        image: "rhe89/hub-spreadsheet-api"